In [20]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_excel("M:/Programme/IHS Global Insight/2015/IHS_LV_Production_Base_Global_2015M04.xlsx", sheet_name="LVP Production")

In [78]:
df = pd.read_excel("M:/Programme/IHS Global Insight/2023/IHS_LV_Production_Base_Global_2023M06.xlsx", sheet_name="LVP Production")

In [95]:
df

3,Core Nameplate Region Mnemonic,Core Nameplate Plant Mnemonic,Mnemonic-Vehicle,Mnemonic-Vehicle/Plant,Mnemonic-Platform,Mnemonic-Plant,Region,Market,Country/Territory,Production Plant,...,Q4 2030,CY 2022,CY 2023,CY 2024,CY 2025,CY 2026,CY 2027,CY 2028,CY 2029,CY 2030
4,1000005,100004113,194102,19410128,13070502,120128,Europe,West Europe,United Kingdom,Dartford,...,0,448,465,366,339,301,294,257,171,0
5,1000010,100008697,2924405,292440570,13127505,120570,Greater China,China,Mainland China,Panyu,...,0,0,0,603,609,3278,3439,3848,1241,0
6,1000014,100007622,655104,65510251,13021504,120251,Japan/Korea,Japan,Japan,Fujisawa,...,0,902,240,0,0,0,0,0,0,0
7,1000017,100011349,2190501,219050154,13177701,120154,North America,NAFTA,United States,Chattanooga,...,0,70946,72852,62562,60424,5074,0,0,0,0
8,1000018,100011834,1486805,148680516,13045005,120516,Greater China,China,Mainland China,Nanjing,...,27459,0,0,69696,139392,148707,126434,118024,112588,103799
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5950,100045953,100052230,2286102,228611516,13093502,121516,Europe,East Europe,Uzbekistan,Syrdarya,...,1312,0,0,0,0,4501,5867,5748,5635,5546
5951,100045955,100052232,2758102,275810051,13071602,120051,Europe,West Europe,Spain,Barcelona,...,0,0,0,0,15696,21395,14574,0,0,0
5952,100045956,100052233,2758302,275830051,13071602,120051,Europe,West Europe,Spain,Barcelona,...,5915,0,0,0,0,0,6039,25953,25820,24650
5953,100045958,100052236,3056201,305621499,13212501,121499,North America,NAFTA,Mexico,Monterrey,...,82995,0,0,0,0,0,0,228593,278133,313350
5954,100045960,100052241,3056202,305621355,13212502,121355,Europe,West Europe,Germany,Gruenheide,...,69971,0,0,0,0,0,0,24377,183481,262215

In [80]:
# where are files description

if df.iat[2, 0] != "NaN":
    df = df[df[df.columns[3]].notna()]
    df.columns = df.iloc[0]
    df = df[1:]

In [93]:
df_long = pd.melt(df, id_vars=df.loc[:, :"Long-Term Risk Rating"], value_vars=df.loc[:,"Long-Term Risk Rating":], var_name="Date and Type", value_name="Quantity")

In [96]:
df_long

,Core Nameplate Region Mnemonic,Core Nameplate Plant Mnemonic,Mnemonic-Vehicle,Mnemonic-Vehicle/Plant,Mnemonic-Platform,Mnemonic-Plant,Region,Market,Country/Territory,Production Plant,...,Global Production Segment,Regional Sales Segment,Global Production Price Class,Global Sales Segment,Global Sales Sub-Segment,Global Sales Price Class,Short-Term Risk Rating,Long-Term Risk Rating,Date and Type,Quantity
0,1000005,100004113,194102,19410128,13070502,120128,Europe,West Europe,United Kingdom,Dartford,...,B-Segment,D-Segment,Premium,D,SPORT,2,2,2,Jan 2022,52
1,1000010,100008697,2924405,292440570,13127505,120570,Greater China,China,Mainland China,Panyu,...,E-Segment,E Full-Size,Entry,D,Car,1,3,3,Jan 2022,0
2,1000014,100007622,655104,65510251,13021504,120251,Japan/Korea,Japan,Japan,Fujisawa,...,Full-Size Full-Frame,LCV,Entry,HVAN,Van,1,2,0,Jan 2022,72
3,1000017,100011349,2190501,219050154,13177701,120154,North America,NAFTA,United States,Chattanooga,...,D-Segment,Mid-Size,Mid,D,SUV,1,3,3,Jan 2022,2068
4,1000018,100011834,1486805,148680516,13045005,120516,Greater China,China,Mainland China,Nanjing,...,D-Segment,E Full-Size,Mid,D,Car,1,1,1,Jan 2022,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553438,100045953,100052230,2286102,228611516,13093502,121516,Europe,East Europe,Uzbekistan,Syrdarya,...,C-Segment,C-Segment,Entry,C,SUV,1,0,0,CY 2030,5546
553439,100045955,100052232,2758102,275810051,13071602,120051,Europe,West Europe,Spain,Barcelona,...,C-Segment,C-Segment,Entry,C,SUV,1,0,0,CY 2030,0
553440,100045956,100052233,2758302,275830051,13071602,120051,Europe,West Europe,Spain,Barcelona,...,C-Segment,C-Segment,Entry,C,SUV,1,0,0,CY 2030,24650
553441,100045958,100052236,3056201,305621499,13212501,121499,North America,NAFTA,Mexico,Monterrey,...,C-Segment,Compact,Premium,C,SUV,1,0,3,CY 2030,313350
553442,100045960,100052241,3056202,305621355,13212502,121355,Europe,West Europe,Germany,Gruenheide,...,C-Segment,C-Segment,Premium,C,SUV,1,0,2,CY 2030,262215

In [196]:
all_files = ["c:/temp/Programme/IHS Global Insight/2015/IHS_LV_Production_Base_Global_2015M04.xlsx", "c:/temp/Programme/IHS Global Insight/2023/IHS_LV_Production_Base_Global_2023M06.xlsx"]
all_files

['c:/temp/Programme/IHS Global Insight/2015/IHS_LV_Production_Base_Global_2015M04.xlsx',
 'c:/temp/Programme/IHS Global Insight/2023/IHS_LV_Production_Base_Global_2023M06.xlsx']

In [234]:
del df_IHS
df_IHS = pd.DataFrame()
for f in all_files:
    print(f)
    df = pd.read_excel(f, sheet_name="LVP Production")
    if pd.isna(df.iat[2, 0]):
          df = df[df[df.columns[3]].notna()]
          df.columns = df.iloc[0]
          df = df[1:]
    df.insert(0, "Filename", f, allow_duplicates=True)
    df_long = pd.melt(df, id_vars=df.loc[:, :"Long-Term Risk Rating"], value_vars=df.loc[:,"Long-Term Risk Rating":], var_name="Date and Type", value_name="Quantity")
    df_IHS = pd.concat([df_IHS, df_long], axis=0, ignore_index=True)
    del df_long
         

#df_from_each_file = (pd.read_excel(f, sheet_name="LVP Production") for f in all_files)
#concatenated_df   = pd.concat(df_from_each_file, ignore_index=True)

c:/temp/Programme/IHS Global Insight/2015/IHS_LV_Production_Base_Global_2015M04.xlsx
c:/temp/Programme/IHS Global Insight/2023/IHS_LV_Production_Base_Global_2023M06.xlsx

In [235]:
df_IHS

,Filename,Mnemonic-Vehicle,Mnemonic-Vehicle/Plant,Mnemonic-Platform,Region,Market,Country,Production Plant,City,Plant State/Province,...,Long-Term Risk Rating,Date and Type,Quantity,Core Nameplate Region Mnemonic,Core Nameplate Plant Mnemonic,Mnemonic-Plant,Country/Territory,Source Plant Country/Territory,Primary Design Country/Territory,Secondary Design Country/Territory
0,c:/temp/Programme/IHS Global Insight/2015/IHS_...,305,30313,13041605,Greater China,China,China,Hangzhou Xiaoshan,Hangzhou,Zhejiang,...,2,Jan 2014,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,c:/temp/Programme/IHS Global Insight/2015/IHS_...,305,30662,13041605,Greater China,Taiwan,Taiwan,San Yi,San Yi,Miaoli,...,2,Jan 2014,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,c:/temp/Programme/IHS Global Insight/2015/IHS_...,407,40390,13016707,Middle East/Africa,Middle East,Iran,Khorasan,Khorasan,Razavi Khorasan,...,0,Jan 2014,3810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,c:/temp/Programme/IHS Global Insight/2015/IHS_...,407,40791,13016707,Middle East/Africa,Middle East,Iran,Tehran,Tehran,Tehran,...,0,Jan 2014,4503,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,c:/temp/Programme/IHS Global Insight/2015/IHS_...,407,40967,13016707,Middle East/Africa,Middle East,Iran,Fars,Fars,Fars,...,0,Jan 2014,657,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1104835,c:/temp/Programme/IHS Global Insight/2023/IHS_...,2286102,228611516,13093502,Europe,East Europe,NaN,Syrdarya,Syrdarya,NaN,...,0,CY 2030,5546,100045953,100052230,121516,Uzbekistan,Uzbekistan,Mainland China,Mainland China
1104836,c:/temp/Programme/IHS Global Insight/2023/IHS_...,2758102,275810051,13071602,Europe,West Europe,NaN,Barcelona,Barcelona,Catalonia,...,0,CY 2030,0,100045955,100052232,120051,Spain,Mainland China,Mainland China,Mainland China
1104837,c:/temp/Programme/IHS Global Insight/2023/IHS_...,2758302,275830051,13071602,Europe,West Europe,NaN,Barcelona,Barcelona,Catalonia,...,0,CY 2030,24650,100045956,100052233,120051,Spain,Mainland China,Mainland China,Mainland China
1104838,c:/temp/Programme/IHS Global Insight/2023/IHS_...,3056201,305621499,13212501,North America,NAFTA,NaN,Monterrey,Santa Catarina,Nuevo Leon,...,3,CY 2030,313350,100045958,100052236,121499,Mexico,Mexico,United States,United States
1104839,c:/temp/Programme/IHS Global Insight/2023/IHS_...,3056202,305621355,13212502,Europe,West Europe,NaN,Gruenheide,Gruenheide,Brandenburg,...,2,CY 2030,262215,100045960,100052241,121355,Germany,Germany,United States,United States

In [232]:
df_IHS.insert(0, "col1", 1, allow_duplicates=True)